---
title: "poem git_01"
author: "eden navarro"
date: "Fall semester"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# Build a Poem with commits
Our project will be done using a sequence of save and commits.

## First Verse 

’Twas brillig, and the slithy toves   
      Did gyre and gimble in the wabe:   
All mimsy were the borogoves,   
      And the mome raths outgrabe.   

“Beware the Jabberwock, my son!   
      The jaws that bite, the claws that catch!   
Beware the Jubjub bird, and shun   
      The frumious Bandersnatch!”   

## Second Verse

Two roads diverged in a yellow wood,  
And sorry I could not travel both  
And be one traveler, long I stood  
And looked down one as far as I could  
To where it bent in the undergrowth;  

Then took the other, as just as fair,  
And having perhaps the better claim,  
Because it was grassy and wanted wear;  
Though as for that the passing there  
Had worn them really about the same,  

## Third Verse

"The sun was shining on the sea,  
      Shining with all his might:   
He did his very best to make   
      The billows smooth and bright —   
And this was odd, because it was   
      The middle of the night.   

The moon was shining sulkily,   
      Because she thought the sun   
Had got no business to be there   
      After the day was done —   
"It's very rude of him," she said,   
      "To come and spoil the fun."   

## Last Verse

How do I love thee? Let me count the ways.   
I love thee to the depth and breadth and height   
My soul can reach, when feeling out of sight   
For the ends of being and ideal grace.   
I love thee to the level of every day’s   
Most quiet need, by sun and candle-light.   
I love thee freely, as men strive for right;   
I love thee purely, as they turn from praise.   
I love thee with the passion put to use   
In my old griefs, and with my childhood’s faith.   
I love thee with a love I seemed to lose   
With my lost saints. I love thee with the breath,   
Smiles, tears, of all my life; and, if God choose,   
I shall but love thee better after death.  

